F04 solo
Bruno-HB/crazee-burger pull request #4
Opened 2023-01-26 17:32 UTC by Bruno-HB

2023-01-26 18:21 UTC, vileaddev requested changes
Bonne PR dans l'ensemble 👏  Des rectifs sur la réusabilité de Logo à apporter :)

2023-01-26 18:21 UTC, vileaddev commented on src/components/pages/login/LoginForm.jsx
> +import { IoChevronForward } from "react-icons/io5";
tu as fais exprès de laisser les points virgules ?

2023-01-26 18:21 UTC, vileaddev commented on src/components/reusable-ui/Logo.jsx
> +    <LogoStyled className="logo" onClick={onClick}>
```suggestion
    <LogoStyled className={className} onClick={onClick}>
```
pour que le Logo soit réutilisable même au niveau du style. Sinon, tu vas forcer les autres dev à entrer à l'intérieur du composant et voir quel est le nom de la class pour changer le style de Logo.

2023-01-26 18:21 UTC, vileaddev commented on src/components/reusable-ui/Logo.jsx
> +export default function Logo({ onClick }) {
```suggestion
export default function Logo({ onClick, className }) {
```

2023-01-26 18:47 UTC, Bruno-HB commented on src/components/pages/login/LoginForm.jsx
> +import { IoChevronForward } from "react-icons/io5";
Oui je m'efforce de les mettre autant que possible

2023-01-26 18:50 UTC, Bruno-HB commented on src/components/reusable-ui/Logo.jsx
> +    <LogoStyled className="logo" onClick={onClick}>
Yep je m'y colle

2023-01-27 07:01 UTC, vileaddev requested changes
Quelques derniers changements et on sera bon 😉

2023-01-27 07:01 UTC, vileaddev commented on src/components/pages/order/Navbar.jsx
> +  min-width: 1400px;
si c'est indiqué dans container, il n'y a pas besoin d'indiquer le width ici car il va automatiquement hériter du width de son parent (ici, container).

2023-01-27 07:01 UTC, vileaddev commented on src/components/pages/order/Main.jsx
> +  min-width: 1400px;
si c'est indiqué dans container, il n'y a pas besoin d'indiquer le width ici car il va automatiquement hériter du width de son parent (ici, container).

2023-01-27 07:01 UTC, vileaddev commented on src/components/pages/order/OrderPage.jsx
> +    min-width: 1400px;
```suggestion
    width: 1400px;
```

2023-01-27 07:01 UTC, vileaddev commented on src/components/pages/order/UserConnected.jsx
> +          <hr />
Un soulignement en CSS aurait été plus approprié et simple dans ce cas ci :
```
        &:hover {
          text-decoration: underline;
          color: ${theme.colors.greyDark};
        }
```


De plus, la vocation de la balise "hr" c'est de marquer une différence entre des parties de texte et pas tellement pour souligner un élément textuel.

<img width="797" alt="image" src="https://user-images.githubusercontent.com/110701253/215027350-7307329d-9f08-4bbf-9185-b1c7819552c3.png">
Source : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr

2023-01-27 07:01 UTC, vileaddev commented on src/components/pages/order/UserConnected.jsx
> +      border: 1px solid ${theme.colors.greyLight};
```suggestion
      border: 1px solid ${theme.colors.greyDark};
```

Ça c'est ma faute, désolé : je t'ai donné la mauvaise valeur dans mes retours précédents

2023-01-30 17:08 UTC, vileaddev approved these changes
Tout est nickel pour moi, tu peux merge Bruno ✅ 😉

2023-01-30 17:09 UTC, merged