F07
Bruno-HB/crazee-burger pull request #7
Opened 2023-04-20 12:15 UTC by Bruno-HB

2023-04-21 16:22 UTC, vileaddev requested changes
Preeeesque parfait ! Deux petits changements et on sera bon 😉

2023-04-21 16:22 UTC, vileaddev commented on src/components/pages/order/Main/Main.js
> +      <div className="menu-and-admin-panel">
Tu peux ranger ça dans un composant <MainRightSide/> : tu verras le CSS en dessous sera du coup plus clair 💯

2023-04-21 16:22 UTC, vileaddev commented on src/components/pages/order/Main/admin/PanelContent.js
> +  const tabSelected = tabs.find((tab) => currentTabSelected === tab.index);
```suggestion
  const tabSelected = getTabsSelected(currentTabSelected)
```
Créé une fonction à part pour que ce soit plus propre. Tu peux ranger cette fonction dans tabsConfig.js

2023-04-21 16:22 UTC, vileaddev commented on src/components/pages/order/Main/admin/PanelTabs.js
> +export default function PanelButtons() {
```suggestion
export default function PanelTabs() {
```

Conserver le même nom de composant et nom de fichier

2023-04-21 16:22 UTC, vileaddev commented on src/components/pages/order/Main/admin/PanelTabs.js
> +            className={
très bien 💯

2023-04-21 16:22 UTC, vileaddev commented on src/components/pages/order/Main/admin/tabsConfig.js
> +export const tabsConfig = [
yes !

2023-04-21 16:27 UTC, Bruno-HB commented on src/components/pages/order/Main/admin/PanelContent.js
> +  const tabSelected = tabs.find((tab) => currentTabSelected === tab.index);
J'suis pas fan, dans l'immédiat je ne l'utilise qu'ici, là faut que je le mette dans un autre fichier, que je rajoute une ligne d'import et que je rappel une fonction. Pour économiser une ligne tu me proposes d'en créer 3 ? Enfin je le vois comme ça peut-être que je suis dans l'erreur

2023-04-25 15:41 UTC, vileaddev approved these changes

2023-04-25 15:42 UTC, merged